[0.140s] Invoking command in '/home/phr/vscode_project/ros2_launch_testing_ws/src/my_testing': PYTEST_ADDOPTS=--tb=short --junit-xml=/home/phr/vscode_project/ros2_launch_testing_ws/build/my_testing/pytest.xml --junit-prefix=my_testing -o cache_dir=/home/phr/vscode_project/ros2_launch_testing_ws/build/my_testing/.pytest_cache PYTHONDONTWRITEBYTECODE=1 /usr/bin/python3 -m pytest
[0.274s] [1m============================= test session starts ==============================[0m
[0.275s] platform linux -- Python 3.10.12, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
[0.276s] cachedir: /home/phr/vscode_project/ros2_launch_testing_ws/build/my_testing/.pytest_cache
[0.276s] rootdir: /home/phr/vscode_project/ros2_launch_testing_ws/src/my_testing
[0.276s] plugins: launch-testing-1.0.10, ament-lint-0.12.14, ament-copyright-0.12.14, ament-xmllint-0.12.14, launch-testing-ros-0.19.10, ament-pep257-0.12.14, ament-flake8-0.12.14, colcon-core-0.19.0, cov-3.0.0
[0.340s] [1mcollecting ... [0m[1m
[0.340s] collected 1 item                                                               [0m
[0.340s] 
[2.440s] test/test_integration.py [31mF[0m[31m                                               [100%][0m
[2.440s] 
[2.440s] =================================== FAILURES ===================================
[2.441s] [31m[1m________________________ launch tests: test_integration ________________________[0m
[2.441s] 
[2.441s] ======================================================================================================================================
[2.441s] FAIL: test_integration.TestIntegration.test_processor_starts_ok
[2.441s] --------------------------------------------------------------------------------------------------------------------------------------
[2.441s] Traceback (most recent call last):
[2.441s]   File "/home/phr/vscode_project/ros2_launch_testing_ws/src/my_testing/test/test_integration.py", line 65, in test_processor_starts_ok
[2.441s]     proc_output.assertWaitFor('数字处理节点已启动，等待接收数字...',process='number_processor',stream='stdout',timeout=1)
[2.441s]   File "/opt/ros/humble/lib/python3.10/site-packages/launch_testing/io_handler.py", line 146, in assertWaitFor
[2.442s]     assert success, 'Waiting for output timed out'
[2.442s] AssertionError: Waiting for output timed out
[2.442s] 
[2.442s] 
[2.442s] ======================================================================================================================================
[2.442s] FAIL: test_integration.TestIntegration.test_publisher_starts_ok
[2.442s] --------------------------------------------------------------------------------------------------------------------------------------
[2.442s] Traceback (most recent call last):
[2.442s]   File "/home/phr/vscode_project/ros2_launch_testing_ws/src/my_testing/test/test_integration.py", line 59, in test_publisher_starts_ok
[2.442s]     proc_output.assertWaitFor('数字发布节点已启动，将从1开始发布...',process='number_publisher',stream='stdout',timeout=1)
[2.442s]   File "/opt/ros/humble/lib/python3.10/site-packages/launch_testing/io_handler.py", line 146, in assertWaitFor
[2.442s]     assert success, 'Waiting for output timed out'
[2.443s] AssertionError: Waiting for output timed out
[2.443s] ----------------------------- Captured stdout call -----------------------------
[2.443s] [INFO] [launch]: All log files can be found below /home/phr/.ros/log/2025-08-05-22-45-50-259460-PHR-55044
[2.443s] [INFO] [launch]: Default logging verbosity is set to INFO
[2.443s] [INFO] [number_publisher-1]: process started with pid [55050]
[2.443s] [INFO] [number_processor-2]: process started with pid [55052]
[2.443s] [number_publisher-1] [INFO] [1754405150.370074247] [number_publisher]: 数字发布节点已启动，将从1开始发布...
[2.443s] [number_processor-2] [INFO] [1754405150.370103929] [number_processor]: 数字处理节点已启动，等待接收数字...
[2.443s] [number_publisher-1] [INFO] [1754405151.365271925] [number_publisher]: 发布: 1
[2.443s] [number_processor-2] [INFO] [1754405151.365749227] [number_processor]: 收到: 1
[2.443s] [number_processor-2] [INFO] [1754405151.366491302] [number_processor]: 发布处理后结果: 3
[2.443s] [INFO] [number_processor-2]: sending signal 'SIGINT' to process[number_processor-2]
[2.444s] [INFO] [number_publisher-1]: sending signal 'SIGINT' to process[number_publisher-1]
[2.444s] [number_processor-2] Traceback (most recent call last):
[2.444s] [number_processor-2]   File "/home/phr/vscode_project/ros2_launch_testing_ws/install/my_algorithms/lib/my_algorithms/number_processor", line 33, in <module>
[2.444s] [number_processor-2]     sys.exit(load_entry_point('my-algorithms==0.0.0', 'console_scripts', 'number_processor')())
[2.444s] [number_processor-2]   File "/home/phr/vscode_project/ros2_launch_testing_ws/install/my_algorithms/lib/python3.10/site-packages/my_algorithms/number_processor_node.py", line 32, in main
[2.444s] [number_processor-2]     rclpy.spin(node)
[2.444s] [number_processor-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 229, in spin
[2.444s] [number_processor-2]     executor.spin_once()
[2.444s] [number_processor-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 751, in spin_once
[2.444s] [number_processor-2]     self._spin_once_impl(timeout_sec)
[2.444s] [number_processor-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 740, in _spin_once_impl
[2.444s] [number_processor-2]     handler, entity, node = self.wait_for_ready_callbacks(timeout_sec=timeout_sec)
[2.444s] [number_processor-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 723, in wait_for_ready_callbacks
[2.444s] [number_processor-2]     return next(self._cb_iter)
[2.445s] [number_processor-2]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 620, in _wait_for_ready_callbacks
[2.445s] [number_processor-2]     wait_set.wait(timeout_nsec)
[2.445s] [number_processor-2] KeyboardInterrupt
[2.445s] [number_publisher-1] Traceback (most recent call last):
[2.445s] [number_publisher-1]   File "/home/phr/vscode_project/ros2_launch_testing_ws/install/my_algorithms/lib/my_algorithms/number_publisher", line 33, in <module>
[2.445s] [number_publisher-1]     sys.exit(load_entry_point('my-algorithms==0.0.0', 'console_scripts', 'number_publisher')())
[2.445s] [number_publisher-1]   File "/home/phr/vscode_project/ros2_launch_testing_ws/install/my_algorithms/lib/python3.10/site-packages/my_algorithms/number_publisher_node.py", line 25, in main
[2.445s] [number_publisher-1]     rclpy.spin(node)
[2.445s] [number_publisher-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 229, in spin
[2.445s] [number_publisher-1]     executor.spin_once()
[2.445s] [number_publisher-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 751, in spin_once
[2.445s] [number_publisher-1]     self._spin_once_impl(timeout_sec)
[2.445s] [number_publisher-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 740, in _spin_once_impl
[2.445s] [number_publisher-1]     handler, entity, node = self.wait_for_ready_callbacks(timeout_sec=timeout_sec)
[2.446s] [number_publisher-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 723, in wait_for_ready_callbacks
[2.446s] [number_publisher-1]     return next(self._cb_iter)
[2.446s] [number_publisher-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 620, in _wait_for_ready_callbacks
[2.446s] [number_publisher-1]     wait_set.wait(timeout_nsec)
[2.446s] [number_publisher-1] KeyboardInterrupt
[2.446s] [ERROR] [number_processor-2]: process has died [pid 55052, exit code -2, cmd '/home/phr/vscode_project/ros2_launch_testing_ws/install/my_algorithms/lib/my_algorithms/number_processor --ros-args -r __node:=number_processor'].
[2.446s] [ERROR] [number_publisher-1]: process has died [pid 55050, exit code -2, cmd '/home/phr/vscode_project/ros2_launch_testing_ws/install/my_algorithms/lib/my_algorithms/number_publisher --ros-args -r __node:=number_publisher'].
[2.446s] ----------------------------- Captured stderr call -----------------------------
[2.446s] test_processor_starts_ok (test_integration.TestIntegration) ... [INFO] [1754405150.301317794] [test_subscriber_node]: 测试节点test_subscriber_node已创建
[2.446s] [INFO] [1754405150.301589690] [test_subscriber_node]: 正在检查 processor 节点的启动日志...
[2.446s] [INFO] [1754405151.306107822] [test_subscriber_node]: 测试结束，销毁测试节点
[2.446s] FAIL
[2.446s] test_publisher_starts_ok (test_integration.TestIntegration) ... [INFO] [1754405151.314048611] [test_subscriber_node]: 测试节点test_subscriber_node已创建
[2.446s] [INFO] [1754405151.314534225] [test_subscriber_node]: 正在检查 publisher 节点的启动日志...
[2.447s] [INFO] [1754405152.318482449] [test_subscriber_node]: 测试结束，销毁测试节点
[2.447s] FAIL
[2.447s] 
[2.447s] ======================================================================
[2.447s] FAIL: test_processor_starts_ok (test_integration.TestIntegration)
[2.447s] ----------------------------------------------------------------------
[2.447s] Traceback (most recent call last):
[2.447s]   File "/home/phr/vscode_project/ros2_launch_testing_ws/src/my_testing/test/test_integration.py", line 65, in test_processor_starts_ok
[2.447s]     proc_output.assertWaitFor('数字处理节点已启动，等待接收数字...',process='number_processor',stream='stdout',timeout=1)
[2.447s]   File "/opt/ros/humble/lib/python3.10/site-packages/launch_testing/io_handler.py", line 146, in assertWaitFor
[2.447s]     assert success, 'Waiting for output timed out'
[2.447s] AssertionError: Waiting for output timed out
[2.447s] 
[2.447s] ======================================================================
[2.447s] FAIL: test_publisher_starts_ok (test_integration.TestIntegration)
[2.448s] ----------------------------------------------------------------------
[2.448s] Traceback (most recent call last):
[2.448s]   File "/home/phr/vscode_project/ros2_launch_testing_ws/src/my_testing/test/test_integration.py", line 59, in test_publisher_starts_ok
[2.448s]     proc_output.assertWaitFor('数字发布节点已启动，将从1开始发布...',process='number_publisher',stream='stdout',timeout=1)
[2.448s]   File "/opt/ros/humble/lib/python3.10/site-packages/launch_testing/io_handler.py", line 146, in assertWaitFor
[2.448s]     assert success, 'Waiting for output timed out'
[2.448s] AssertionError: Waiting for output timed out
[2.448s] 
[2.448s] ----------------------------------------------------------------------
[2.448s] Ran 2 tests in 2.051s
[2.448s] 
[2.448s] FAILED (failures=2)
[2.448s] 
[2.448s] ----------------------------------------------------------------------
[2.449s] Ran 0 tests in 0.000s
[2.449s] 
[2.449s] OK
[2.449s] - generated xml file: /home/phr/vscode_project/ros2_launch_testing_ws/build/my_testing/pytest.xml -
[2.449s] =========================== short test summary info ============================
[2.449s] FAILED test/test_integration.py::test_integration - test_integration.TestInte...
[2.449s] [31m============================== [31m[1m1 failed[0m[31m in 2.17s[0m[31m ===============================[0m
[2.604s] Invoked command in '/home/phr/vscode_project/ros2_launch_testing_ws/src/my_testing' returned '1': PYTEST_ADDOPTS=--tb=short --junit-xml=/home/phr/vscode_project/ros2_launch_testing_ws/build/my_testing/pytest.xml --junit-prefix=my_testing -o cache_dir=/home/phr/vscode_project/ros2_launch_testing_ws/build/my_testing/.pytest_cache PYTHONDONTWRITEBYTECODE=1 /usr/bin/python3 -m pytest
