[1m============================= test session starts ==============================[0m
platform linux -- Python 3.10.12, pytest-6.2.5, py-1.10.0, pluggy-0.13.0
cachedir: /home/phr/vscode_project/ros2_launch_testing_ws/build/my_testing/.pytest_cache
rootdir: /home/phr/vscode_project/ros2_launch_testing_ws/src/my_testing
plugins: launch-testing-1.0.10, ament-lint-0.12.14, ament-copyright-0.12.14, ament-xmllint-0.12.14, launch-testing-ros-0.19.10, ament-pep257-0.12.14, ament-flake8-0.12.14, colcon-core-0.19.0, cov-3.0.0
[1mcollecting ... [0m[1m
collected 1 item                                                               [0m

test/test_processor_service.py [INFO] [launch]: All log files can be found below /home/phr/.ros/log/2025-08-07-13-56-04-001172-PHR-23800
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [number_processor-1]: process started with pid [23807]
[number_processor-1] [INFO] [1754546164.109073334] [number_processor_service_node]: 数字处理服务节点已启动，等待请求...
test_service (test_processor_service.TestProcessorService) ... [0m[INFO] [1754546164.294786215] [service_client_test_node]: 正在发送请求: 10...[0m
[number_processor-1] [INFO] [1754546164.295444009] [number_processor_service_node]: 收到服务请求，输入数字: 10
[number_processor-1] [INFO] [1754546164.295713538] [number_processor_service_node]: 正在返回处理结果: 30
[0m[INFO] [1754546164.296320276] [service_client_test_node]: 测试用例通过: 输入=10, 响应=30[0m
[0m[INFO] [1754546164.296542311] [service_client_test_node]: 正在发送请求: -5...[0m
[number_processor-1] [INFO] [1754546164.296874771] [number_processor_service_node]: 收到服务请求，输入数字: -5
[number_processor-1] [INFO] [1754546164.297126490] [number_processor_service_node]: 正在返回处理结果: -15
[0m[INFO] [1754546164.297561061] [service_client_test_node]: 测试用例通过: 输入=-5, 响应=-15[0m
[0m[INFO] [1754546164.297770036] [service_client_test_node]: 正在发送请求: 0...[0m
[number_processor-1] [INFO] [1754546164.298091809] [number_processor_service_node]: 收到服务请求，输入数字: 0
FAIL

======================================================================
FAIL: test_service (test_processor_service.TestProcessorService)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/phr/vscode_project/ros2_launch_testing_ws/src/my_testing/test/test_processor_service.py", line 70, in test_service
    self.assertEqual(
AssertionError: 1 != 0 : 输入 0 时，响应结果不正确！

----------------------------------------------------------------------
Ran 1 test in 0.291s

FAILED (failures=1)
[INFO] [number_processor-1]: sending signal 'SIGINT' to process[number_processor-1]
[number_processor-1] Traceback (most recent call last):
[number_processor-1]   File "/home/phr/vscode_project/ros2_launch_testing_ws/install/my_algorithms/lib/my_algorithms/number_processor", line 33, in <module>
[number_processor-1]     sys.exit(load_entry_point('my-algorithms==0.0.0', 'console_scripts', 'number_processor')())
[number_processor-1]   File "/home/phr/vscode_project/ros2_launch_testing_ws/install/my_algorithms/lib/python3.10/site-packages/my_algorithms/number_processor_node.py", line 42, in main
[number_processor-1]     rclpy.spin(node) 
[number_processor-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 229, in spin
[number_processor-1]     executor.spin_once()
[number_processor-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 751, in spin_once
[number_processor-1]     self._spin_once_impl(timeout_sec)
[number_processor-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 740, in _spin_once_impl
[number_processor-1]     handler, entity, node = self.wait_for_ready_callbacks(timeout_sec=timeout_sec)
[number_processor-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 723, in wait_for_ready_callbacks
[number_processor-1]     return next(self._cb_iter)
[number_processor-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 620, in _wait_for_ready_callbacks
[number_processor-1]     wait_set.wait(timeout_nsec)
[number_processor-1] KeyboardInterrupt
[ERROR] [number_processor-1]: process has died [pid 23807, exit code -2, cmd '/home/phr/vscode_project/ros2_launch_testing_ws/install/my_algorithms/lib/my_algorithms/number_processor --ros-args -r __node:=number_processor_service_node'].

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
[31mF[0m

=================================== FAILURES ===================================
[31m[1m_____________________ launch tests: test_processor_service _____________________[0m

================================================================================================================================
FAIL: test_processor_service.TestProcessorService.test_service
--------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/phr/vscode_project/ros2_launch_testing_ws/src/my_testing/test/test_processor_service.py", line 70, in test_service
    self.assertEqual(
AssertionError: 1 != 0 : 输入 0 时，响应结果不正确！
- generated xml file: /home/phr/vscode_project/ros2_launch_testing_ws/build/my_testing/pytest.xml -
=========================== short test summary info ============================
FAILED test/test_processor_service.py::test_processor_service - test_processo...
[31m============================== [31m[1m1 failed[0m[31m in 0.38s[0m[31m ===============================[0m
